version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@7.0.0
  nx: nrwl/nx@1.6.0

jobs:
  nx-build:
    docker:
      - image: cimg/node:16.16.0
    resource_class: medium
    steps:
      - checkout
      # - run: |
      #     npm install -g turbo
      #     turbo prune --scope=@circleo/web --docker
      - run:
          name: build proj
          command: yarn build
workflows:
  build_and_deploy:
    jobs:
      - nx-build:
          # deploy-stage: test
          filters:
            branches:
              only:
                - circleci-project-setup
                - main
      # - run:
      #     name: start
      #     command: yarn start
      # - run:
      #     name: Prepare shell commands
      #     command: chmod +x ./deploy/deploy.sh
      # - run:
      #     name: Run deploy scripts
      #     command: ./deploy/deploy.sh